name: feetly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-162.0.dev

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  lottie: ^3.3.1
  flutter_svg: ^2.2.1
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  video_player: ^2.10.0
  chewie: ^1.13.0
  camera: ^0.11.2
  camera_android: ^0.10.10+1
  google_mlkit_pose_detection: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/.
    - assets/animations/Loading.json
    - assets/icons/.
    - assets/videos/.
    - assets/thumbnails/.
    
