// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu3DHMZCyFyQbRzXWK5Lv1zPFBt91LZZs',
    appId: '1:1013278180338:web:18560107a195f66d80a16b',
    messagingSenderId: '1013278180338',
    projectId: 'feetly-f6d34',
    authDomain: 'feetly-f6d34.firebaseapp.com',
    storageBucket: 'feetly-f6d34.firebasestorage.app',
    measurementId: 'G-1WK3Z0Q58H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChzkIGZGXjNuwCedSvjk1bJoyr6M2tOJw',
    appId: '1:551988849500:android:cfc29d021e442e066aaf99',
    messagingSenderId: '551988849500',
    projectId: 'feetly-e0551',
    storageBucket: 'feetly-e0551.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAITIy5Hp9hxIzoUDoTkaYZLIPG-GqtePk',
    appId: '1:551988849500:ios:4547706cdb3048db6aaf99',
    messagingSenderId: '551988849500',
    projectId: 'feetly-e0551',
    storageBucket: 'feetly-e0551.firebasestorage.app',
    iosBundleId: 'com.example.feetly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7L0TZjM6Gf75c21s7Nz4yZI2hXczzjK4',
    appId: '1:1013278180338:ios:22757f8e79851d9180a16b',
    messagingSenderId: '1013278180338',
    projectId: 'feetly-f6d34',
    storageBucket: 'feetly-f6d34.firebasestorage.app',
    iosBundleId: 'com.example.feetly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu3DHMZCyFyQbRzXWK5Lv1zPFBt91LZZs',
    appId: '1:1013278180338:web:d78a9be864b224fb80a16b',
    messagingSenderId: '1013278180338',
    projectId: 'feetly-f6d34',
    authDomain: 'feetly-f6d34.firebaseapp.com',
    storageBucket: 'feetly-f6d34.firebasestorage.app',
    measurementId: 'G-CG2B5VCT2Q',
  );
}